### ISSUE TITLE
Creating a user profile

### ISSUE THREAD

**Issue by MariaZakharovaCoding** [ZakharovAndrew/yii2-user#2]
I would like to have a user profile. Are there any plans to create one?

**Comment by ZakharovAndrew** [comment]
The plans include creating a user profile, but after eliminating bugs related to access.

**Comment by ZakharovAndrew** [comment]
I'm getting closer to creating a user profile in the module

**Comment by ZakharovAndrew** [comment]
The user profile has appeared in the module.
